site_name: SPAM-DFBA

theme:
  name: "material"

plugins:
  - mkdocstrings

nav:
  - Main : index.md
  - Installation : Installation.md
  - API : API.md
  - Case Study - Starch Amylase : case_studies_Starch_Amylase.html
  - Case Study - Toy NECom : case_studies_NECOM.html
  - Case Study - Ecoli GEM : case_studies_ecoli_GEM.html
  - Statistical Analysis: stats.html
  

